# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfd3f2e60b997eb64a3935ca6dbd505ea06b415579de73804cb8adf73c85d7f0e06cbc973dd1fa967e2d86c0376b1a7134ef2392cac6d57d7ab2d8f6500e0a71

test:
  secret_key_base: 58b541334cefe1badfde9e93cc322d231622eeb8e7a621cd303ff58e934298635d3bb7b500bcdc1cdb6c950e0e53d3d474e140806562e508a86aef5b746d0669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
